# routes:
#   - src: /
#     dest: /index.html

# runtime: nodejs8
# instance_class: F1
# automatic_scaling:
#   max_instances: 1

# handlers:
#   - url: /
#     static_files: build/index.html
#     upload: build/index.html


instance_class: F1
automatic_scaling:
  max_instances: 1

handlers:
  - url: /.*
    static_files: build/index.html
    upload: build/index.html